-- Core schema for PDF Lovers (Supabase Postgres)

create extension if not exists pg_trgm;
create extension if not exists unaccent;

create table if not exists public.pdfs (
  id bigint generated by default as identity primary key,
  title text not null,
  author text,
  category text,
  tags text[] default '{}'::text[],
  summary text,
  cover_image_url text,
  page_count integer,
  rating numeric(2,1),
  published_at date,
  smart_link text,
  download_url text,
  is_featured boolean not null default false,
  download_count bigint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  search_document tsvector generated always as (
    setweight(to_tsvector('english', unaccent(coalesce(title, ''))), 'A') ||
    setweight(to_tsvector('english', unaccent(coalesce(author, ''))), 'B') ||
    setweight(to_tsvector('english', unaccent(coalesce(category, ''))), 'B') ||
    setweight(to_tsvector('english', unaccent(coalesce(array_to_string(tags, ' '), ''))), 'B') ||
    setweight(to_tsvector('english', unaccent(coalesce(summary, ''))), 'C')
  ) stored
);

create index if not exists idx_pdfs_search_document on public.pdfs using gin (search_document);
create index if not exists idx_pdfs_category on public.pdfs (category);
create index if not exists idx_pdfs_published_at on public.pdfs (published_at desc);
create index if not exists idx_pdfs_download_count on public.pdfs (download_count desc);

create table if not exists public.download_events (
  id bigint generated by default as identity primary key,
  pdf_id bigint not null references public.pdfs(id) on delete cascade,
  click_stage text not null check (click_stage in ('smart', 'direct')),
  referer text,
  user_agent text,
  ip_address text,
  created_at timestamptz not null default now()
);

create index if not exists idx_download_events_pdf_id on public.download_events (pdf_id);
create index if not exists idx_download_events_created_at on public.download_events (created_at desc);

create table if not exists public.pdf_requests (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  details text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  message text not null,
  created_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_pdfs_set_updated_at on public.pdfs;
create trigger trg_pdfs_set_updated_at
before update on public.pdfs
for each row
execute function public.set_updated_at();
