-- Core schema for PDF Lovers (Supabase Postgres)

create extension if not exists pg_trgm;
create extension if not exists pgcrypto;

create table if not exists public.pdfs (
  id bigint generated by default as identity primary key,
  public_id uuid not null default gen_random_uuid(),
  title text not null,
  author text,
  category text,
  tags text[] default '{}'::text[],
  summary text,
  cover_image_url text,
  page_count integer,
  rating numeric(2,1),
  published_at date,
  smart_link text,
  download_url text,
  is_featured boolean not null default false,
  download_count bigint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  search_document tsvector
);

create index if not exists idx_pdfs_search_document on public.pdfs using gin (search_document);
create unique index if not exists idx_pdfs_public_id on public.pdfs (public_id);
create index if not exists idx_pdfs_category on public.pdfs (category);
create index if not exists idx_pdfs_published_at on public.pdfs (published_at desc);
create index if not exists idx_pdfs_download_count on public.pdfs (download_count desc);

create table if not exists public.download_events (
  id bigint generated by default as identity primary key,
  pdf_id bigint not null references public.pdfs(id) on delete cascade,
  click_stage text not null check (click_stage in ('smart', 'direct')),
  referer text,
  user_agent text,
  ip_address text,
  created_at timestamptz not null default now()
);

create index if not exists idx_download_events_pdf_id on public.download_events (pdf_id);
create index if not exists idx_download_events_created_at on public.download_events (created_at desc);

create table if not exists public.pdf_requests (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  details text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  message text not null,
  created_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create or replace function public.update_pdfs_search_document()
returns trigger
language plpgsql
as $$
begin
  new.search_document :=
    setweight(to_tsvector('english', coalesce(new.title, '')), 'A') ||
    setweight(to_tsvector('english', coalesce(new.author, '')), 'B') ||
    setweight(to_tsvector('english', coalesce(new.category, '')), 'B') ||
    setweight(to_tsvector('english', coalesce(array_to_string(new.tags, ' '), '')), 'B') ||
    setweight(to_tsvector('english', coalesce(new.summary, '')), 'C');
  return new;
end;
$$;

drop trigger if exists trg_pdfs_search_document on public.pdfs;
create trigger trg_pdfs_search_document
before insert or update of title, author, category, tags, summary
on public.pdfs
for each row
execute function public.update_pdfs_search_document();

drop trigger if exists trg_pdfs_set_updated_at on public.pdfs;
create trigger trg_pdfs_set_updated_at
before update on public.pdfs
for each row
execute function public.set_updated_at();

update public.pdfs
set search_document =
  setweight(to_tsvector('english', coalesce(title, '')), 'A') ||
  setweight(to_tsvector('english', coalesce(author, '')), 'B') ||
  setweight(to_tsvector('english', coalesce(category, '')), 'B') ||
  setweight(to_tsvector('english', coalesce(array_to_string(tags, ' '), '')), 'B') ||
  setweight(to_tsvector('english', coalesce(summary, '')), 'C')
where search_document is null;
